name: Pull-request for .NET + Java
on:
  push:
    branches:
      - dev
jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code  
        uses: actions/checkout@v4

      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build .NET Application
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o publish_output

      - name: Upload .NET Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish_output

  build_java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Package Java
        run: mvn clean package
        working-directory: samples_java  # <-- path to pom.xml

      - name: Upload Java Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: samples_java/target/*.jar
